### ISSUE TITLE
Don't use "fancy quotes"

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#406] opened 2017-12-19 17:53 UTC
Fancy quotes like ’ instead of ' break code. It would be best to avoid them so that samples can always be copied and pasted. 

This came up working on `launch-apps-from-collect` where I noticed that single quotes in XLSForm samples were converted to fancy ones.

**Comment by adammichaelwood** [comment] 2018-06-08 16:34
This was a duplicate of #513, which was closed in #521.

**Closed by adammichaelwood** 2018-06-08 16:34 UTC
