### ISSUE TITLE
Pull in docs from community sources

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#10] opened 2017-06-21 21:39 UTC
For each of these, we need to first ask permission!
- [x] https://www.google.com/earth/outreach/learn
- [x] http://sudan.validmeasures.org/category/open-data-kit
- [x] http://opendatakit.lshtm.ac.uk/what-do-i-need
- [x] http://odk.acf-e.org/odk/start_here.html
- [ ] https://opendatakit.org/help/training-guides (lots o links here)

**Comment by Divya063** [comment] 2017-10-02 16:58
@yanokwa I would like to work on this

**Comment by yanokwa** [comment] 2017-10-06 20:53
@adammichaelwood Can you review these sources and see if it makes sense to pull some of these in? If so, a good first set might be to reach out to the various authors and ask for permission to use their content. I'm glad to be cc'ed on those emails or find the right people to contact if that'd be helpful.

Once we have that, then it might be easier to break this up into an issue per source and tag those as contributor friendly for folks like @Divya063.

**Comment by adammichaelwood** [comment] 2017-10-10 16:26
- https://www.google.com/earth/outreach/learn is actually several pages:
   - https://www.google.com/earth/outreach/learn/getting-started-with-mobile-data-collection-using-odk/ -- Basically a Getting Started Guide that reproduces information we already have
   - https://www.google.com/earth/outreach/learn/odk-collect-and-google-drive-integration-to-store-and-manage-your-data/ -- About using Google Drive as the data storage solution. This addresses #164, and the docs was PRed in #180, but @nadaa did not provide follow up about asking Google for permission.

**Comment by adammichaelwood** [comment] 2017-10-10 16:42
Just some notes as I go through these...

https://www.google.com/earth/outreach/learn is actually several pages:

  - https://www.google.com/earth/outreach/learn/getting-started-with-mobile-data-collection-using-odk/ -- Basically a Getting Started Guide that reproduces information we already have

  - https://www.google.com/earth/outreach/learn/odk-collect-and-google-drive-integration-to-store-and-manage-your-data/ -- About using Google Drive as the data storage solution. 
     - This addresses #164, and the docs was PRed in #180, but @nadaa did not provide follow up about asking Google for permission.
     - As I noted in the PR #180, even if we could track down how to get permission from Google, I think this doc would be better if it were written from scratch.

  - https://www.google.com/earth/outreach/learn/mobile-data-collection-using-odk-collect/ | https://www.google.com/earth/outreach/learn/visualize-field-data-in-google-earth-and-fusion-tables/

      - These two are duplicate copies of the same doc, about visualizing ODK data in Fusion Tables and Maps. Cool info, but the doc itself is confusing and poorly organized. I think simply starting from scratch on this topic would be worthwhile.
       - I've opened #288 for this.

  - https://www.google.com/earth/outreach/learn/manage-your-data-with-odk-aggregate/ -- This is sort of like a user guide for Aggregate. I don't think pulling this in wholesale is a good idea, but whoever writes the Aggregate Guide #249 should have this as a source.

**Comment by adammichaelwood** [comment] 2017-10-12 20:09
http://sudan.validmeasures.org/category/open-data-kit

This is a whole category of blog posts on ODK. Some of them are about using Android features (like changing the language setting on a phone) and there's a couple about a 3rd party alternative to Aggregate (called Form Hub). The relevant ones just duplicate info we have already, but do so in excruciating detail.

**Comment by adammichaelwood** [comment] 2017-10-12 20:15
http://opendatakit.lshtm.ac.uk/what-do-i-need

This material mostly duplicates stuff we already have, and also has info about using ODK specifically at LSHTM -- like how to connect to their shared server.

**Comment by adammichaelwood** [comment] 2017-10-13 17:35
http://odk.acf-e.org/odk/start_here.html

The docs here are kind of a mess --- the organization is all over the place. So it's hard to know everything that is available. But it seems like the info is either very basic (And duplicate of things we have), or covers specific issues with their org. processes.

**Comment by adammichaelwood** [comment] 2017-10-13 18:43
- Yaw Anokwa from Nafundi: [Replacing paper forms with smart forms on phones and                                                                                        
    tablets](https://speakerdeck.com/nafundi/replacing-paper-forms-with-smart-forms-on-phones-and-tablets)
 - Emily Kumpel and Berkeley in India: [Deployment Manual](http://ekumpel.wordpress.com/2011/02/13/135/)
 - Neil Hendrick and Berkeley HRC in Liberia: [Deployment Notes](https://groups.google.com/group/opendatakit/browse_thread/thread/482acd1de955692e)
 - Andrew Azman and Johns Hopkins in Ghana: [Deployment Notes](https://groups.google.com/group/opendatakit/browse_thread/thread/482acd1de955692e)
 - Evelyn Castle in Nigeria: 
     - [Training Manual](http://www.evelyncastle.com/wp-content/uploads/2012/01/Users_Manual.pdf),
     - Videos on [using Android](https://www.youtube.com/watch?v=MBVSrM9MogI)
     - [filling out forms](https://www.youtube.com/watch?v=IzhgvhB7nLE)
     - [sending forms](https://www.youtube.com/watch?v=WWEcbRkBwwA)
 - ViewWorld: Videos on how to 
     - [build a simple form](https://www.youtube.com/watch?v=Tuw9I_WZI7w), 
     - [export a XM form](https://www.youtube.com/watch?v=uDxYlR-T9L0)
     - [build more complex forms](https://www.youtube.com/watch?v=7kTCMWXAfR0).
 - CartONG and UN Refugee Agency in Kenya and Serbia: 
     - [Deployment
Manual](https://docs.google.com/document/d/1RjY_KImZbXZchyPeinLXXrqvm_laHzTVYK5yzl6kvPM/edit?hl=en#),
     - [Training Slides](https://docs.google.com/present/view?id=dfzctfjq_419m5wsmgz),
     - [Emulator Tutorial](https://docs.google.com/document/pub?id=18LbrTnyfJkG0CZDLMuVVzsU7ffNDnvzHJXEQ7poseuA),
     - [Form Creation Tutorial](https://docs.google.com/document/pub?id=1SVryUoe2FFqqgFDudpGoEmFNJ2PBdT1_9k--Z7SXewA),
     - [Other Tips](http://humanitarian-android.org/Main_Page)
 - Chris Kelley and RTI: [Setup Notes](http://www.ictedge.org/node/894)
 - Google Earth Outreach: [Tutorials](http://www.google.com/earth/outreach/tutorials/index.html#odk)
 - AfSIS Blog: [Deployment Notes](http://africasoils.net/labs/?s=ict4ag), [Training Guide](http://africasoils.net/labs/mobile/our-odk-training-experience-materials-included/)
 - Doug Browning: [Setup Notes](https://sites.google.com/site/dougbrowningportfolio/Resources/mobile-gis)
 - Chris Wilson: [Training Guide](http://blog.aptivate.org/2011/12/05/rough-guidehttp://wphostreviews.com/mappress-to-rural-data-collection-with-odk/)
 - Samantha Elghanayan: [ODK Collect and ODK Briefcase Starter Guide](https://groups.google.com/d/topic/opendatakit/Exx9EpusBiA/discussion)
 - Joe Doherty at CalGIS: [Mobile Meets the  Cloud](http://opendatakit.org/wp-content/uploads/2013/04/CALGIS-Mobile-Meets-the-Cloud.pdf)
 - Tania Bird: [Step by step for using ODK from start to finish](https://groups.google.com/d/msg/opendatakit/wxXDlVl83FI/gusIaaqdYooJ)
 - Jorge Durand Zurdo and ACF: [Online training modules and video](http://odk.acf-e.org/odk/start_here.html)

**Comment by adammichaelwood** [comment] 2018-03-23 15:54
I haven't found much (if anything) in all of this that seems relevant to merge in.

Before I close this ----

Do we want docs maintain a list of third-party resources, tutorials, etc?

Pro:

 - could add value to the community
 - even very basic stuff might be helpful, as it provides the same info from a different perspective

Cons:

 - potentially time consuming to keep accurate

**Comment by lognaturel** [comment] 2018-03-23 16:04
Perhaps the external resources could go on the website? "Official docs are docs.opendatakit.org. Here are some community resources: ... Want to add a resource or remove one that's out of date, issue a website pull request, etc"

That way the docs stay focused and accurate.

**Comment by adammichaelwood** [comment] 2018-03-23 20:38
That sounds reasonable to me.

I'm closing this issue.

**Closed by adammichaelwood** 2018-03-23 20:38 UTC
Labels: discussion
