### ISSUE TITLE
Clarify why menuselection labeling is used

### ISSUE THREAD

**Issue by mish24** [opendatakit/docs#171] opened 2017-09-16 08:35 UTC
Right now in the docs, wherever `:menuselection:` label is used, the text appears as normal text. Menuselection is used when we need to provide instructions like Select "A ----> B -----> C". If not, these should be replaced by `:guilabel:` only. 
For reference look at https://docs.opendatakit.org/collect-install/
Notice that in `warning` given at the end, the `Server settings` and `Other` are buttons, but they're represented as normal text

**Comment by mish24** [comment] 2017-09-16 09:15
I just noticed #109 is for styling `:menuselection:`, but when and where should we use it?

**Comment by adammichaelwood** [comment] 2017-09-16 17:00
This is a duplicate of #109

**Closed by adammichaelwood** 2017-09-16 17:00 UTC
