### ISSUE TITLE
Old docs should say "deprecated" and link to new docs

### ISSUE THREAD

**Issue by hooverlunch** [opendatakit/docs#519] opened 2018-02-12 20:15 UTC
The old docs e.g. https://opendatakit.org/help/form-design/body/ are deprecated right? Or not yet?

The pagerank of the new docs is not super great. That might help by deprecating the old ones. But maybe the new ones are still in beta? Apologies if so.

**Comment by adammichaelwood** [comment] 2018-02-12 20:26
Thanks.

Most of the docs pages have deprecation links. We are planning to 301 those.

The page you mention in particular is part of a collection of docs about editing XForms XML directly. There has been an ongoing conversation about how much of that info should be part of the docs, as opposed to being a part of the [ODK XForm Specification](https://opendatakit.github.io/xforms-spec/).

cf. #239 (Closing this issue as a duplicate of that one.)

**Closed by adammichaelwood** 2018-02-12 20:26 UTC
