### ISSUE TITLE
Build failing because of bad png?

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#323] opened 2017-10-24 19:36 UTC
The command that is preventing master from shipping releases is
`pngquant $HOME/docs/build/_images/jump*.png --force --ext .png`

It fails with on remote server (Ubuntu 14.04)
```
jumpmenu.png:
  error: Not a PNG file
  error: rwpng_read_image() error 25
jumpscreen.png:
  error: Not a PNG file
  error: rwpng_read_image() error 25
```
This command works fine on my local machine (macOS 10.13). 

* I've confirmed that the command fails on remote source image
`pngquant ~/docs/img/collect-forms/jump*.png --verbose`
* I've confirmed that the command fails on remote build image 
`pngquant ~/docs/build/_images/jump*.png --verbose`
* I've confirmed that the MD5 hashes between local/remote are the same.
```
MD5 (jumpmenu.png) = 1a4caec3e2c4bc858b6ea8c1d1b2611c
MD5 (jumpscreen.png) = 700448df36766436573aa0f6cd7e739a
```

* Remote pngquant is 2.0.1 and local pngquant is 2.9.1, but I've built from source on remote (v2.10.2) and that fails too.
```
/home/ubuntu/docs/img/collect-forms/jumpmenu.png:
  error: Not a PNG file (libpng failed)
  error: cannot decode image jumpmenu.png
/home/ubuntu/docs/img/collect-forms/jumpscreen.png:
  error: Not a PNG file (libpng failed)
  error: cannot decode image jumpscreen.png
```

https://github.com/opendatakit/docs/pull/318/files is the pull request that is the root of this problem. @adammichaelwood just to fix this, can you send in a PR with an updated image, so we can fix the build?

**Comment by adammichaelwood** [comment] 2017-10-24 19:51
These images were created by @troublemagnet

**Comment by adammichaelwood** [comment] 2017-10-24 19:53
These images were created by @troublemagnet 

I can reproduce them... but is there any way to find out why they are failing?
The images don't seem corrupt otherwise (they are viewable in GH and locally when I build)

**Comment by yanokwa** [comment] 2017-10-24 19:58
Yeah, I can't repro it either and I've spent way too much time on it. I'd propose you take new screenshots because we know your process works and then merge that in to fix the build.

Then I have a PR (https://github.com/opendatakit/docs/pull/324) that will check "bad" PNGs in the future and we can try to repro it then.

**Comment by adammichaelwood** [comment] 2017-10-24 20:14
Rather than recreate the images, I thought it would be faster to pull them into gimp and re-export them as new pngs.

when i opened them png in gimp, it appears to have an odd color profile:

```
sRGB IEC611966-2-1 black scaled
```
This appears to be an older color standard then the one more commonly used by current image editing software. Which may be why pngquant does not support it, even though web browsers and image viewers do.

My *guess* is that the problem is @troublemagnet's Android device. And the smaller icon image wasn't affected because that was cropped in an editor that exported the modern RGB profile.

The workaround for affected committers is to open in gimp or PS and re-export before committing. There may be a command line tool to do the same. (Maybe Python Pillow?).

**Comment by adammichaelwood** [comment] 2017-10-24 20:27
I am having a git problem...

there seems to be a previously committed (?) image file which is not in the repo anymore, causing a problem with `git push`

```
$ git push origin jump -f
 open /Users/adamwood/odk/odk-docs/img/collect-forms/jumpbutton.png: no such file or directory
 error: failed to push some refs to 'https://github.com/adammichaelwood/odk-docs.git'
```

@yanokwa @ln any help?

**Comment by yanokwa** [comment] 2017-10-24 20:28
Let's talk in Slack. In the meanwhile, can you upload the Gimped images here?

**Comment by adammichaelwood** [comment] 2017-10-24 20:29
![jumpmenu](https://user-images.githubusercontent.com/1776241/31966396-6a2f76ca-b8bf-11e7-87c4-ef69d37353f3.png)
![jumpscreen](https://user-images.githubusercontent.com/1776241/31966397-6a49bab2-b8bf-11e7-9286-7818b056efd6.png)

**Comment by yanokwa** [comment] 2017-10-24 20:37
I can confirm that Adam's fix of opening in Gimp and re-exporting as PNGs works. So yeah, must have been an odd color profile. @troublemagnet How did you create this PNG? If it was on a device, what was the device and version of Android?

I still propose that we use pnquant to check this on every PR (https://github.com/opendatakit/docs/pull/324) and we'll know whenever there is a bad PNG.

**Closed** 2017-10-24 20:42 UTC
Labels: in progress

**Comment by troublemagnet** [comment] 2017-10-25 10:57
@yanokwa I'm using Moto X Style, Android 7.0.  Apologies for the inconvenience caused.
